//  kurono os - embedded alpine linux guest data
//
//  the alpine linux kernel (vmlinuz-virt) and initramfs are converted
//  from binary files to elf objects via objcopy and linked directly into
//  the kurono kernel image.  this header exposes the start/end symbols
//  generated by objcopy so the hypervisor can locate them at boot.
//
//  build: see the alpine_* rules in src/makefile.
#pragma once
#include <stdint.h>

//
// objcopy names them after the input filename with non-identifier chars
// replaced by underscores:
//   vmlinuz-virt  → _binary_vmlinuz_virt_{start,end,size}
//   initramfs-virt→ _binary_initramfs_virt_{start,end,size}
//
// we use 'extern "c"' to prevent c++ name mangling so the linker can
// resolve them against the objcopy-generated symbols.

extern "C" {
    // alpine linux 6.x virt kernel - bzimage
    // __attribute__((weak)): resolves to null if alpine objects aren't linked
    extern const uint8_t _binary_vmlinuz_virt_start[] __attribute__((weak));
    extern const uint8_t _binary_vmlinuz_virt_end[]   __attribute__((weak));

    // alpine linux initramfs (mkinitfs output - modules + init scripts)
    extern const uint8_t _binary_initramfs_virt_start[] __attribute__((weak));
    extern const uint8_t _binary_initramfs_virt_end[]   __attribute__((weak));
}

static inline uint32_t alpine_kernel_size() {
    return (uint32_t)((uintptr_t)_binary_vmlinuz_virt_end -
                      (uintptr_t)_binary_vmlinuz_virt_start);
}

static inline uint32_t alpine_initramfs_size() {
    return (uint32_t)((uintptr_t)_binary_initramfs_virt_end -
                      (uintptr_t)_binary_initramfs_virt_start);
}

static inline const uint8_t* alpine_kernel_data() {
    return _binary_vmlinuz_virt_start;
}

static inline const uint8_t* alpine_initramfs_data() {
    return _binary_initramfs_virt_start;
}

static inline bool alpine_data_available() {
    return _binary_vmlinuz_virt_start != nullptr &&
           _binary_initramfs_virt_start != nullptr;
}
