//  kurono os  -  linux network stack bridge  -  implementation

#include "linux_netbridge.h"
#include "../kernel/heap.h"
#include "../drivers/timer.h"
#include "../drivers/serial.h"
#include "../fs/kvfs.h"
#include "../net/network.h"
#include "../net/tcpip.h"
#include "../shell/shell.h"
#include "../proc/kernel_locks.h"

// every MUTATING TCPStack call from the bridge runs under g_net_lock (the
// leaf lock the NetworkProcess tick already takes)  -  linux syscalls run on
// the bsp AND the aps truly parallel to that tick. readiness/rx-count checks
// stay lock-free single-word reads (bounded staleness, next poll re-reads).
// the bridge is strictly NON-BLOCKING: TCPStack's internal blocking waits
// (Connect/Accept/Send window-full) call PumpUI, which is unsafe off the
// bsp, so every path here pre-checks state to keep those unreachable. (satoru)

LinuxSocket       LinuxNetBridge::sockets[LNET_MAX_SOCKETS];
int               LinuxNetBridge::socket_count = 0;
LinuxNetInterface LinuxNetBridge::interfaces[LNET_MAX_INTERFACES];
int               LinuxNetBridge::iface_count = 0;
uint32_t          LinuxNetBridge::dns_primary = 0x08080808;   // 8.8.8.8
uint32_t          LinuxNetBridge::dns_secondary = 0x08080404; // 8.8.4.4

int LinuxNetBridge::pa(char* out, int pos, int mx, const char* s) {
    while (*s && pos < mx - 1) out[pos++] = *s++;
    out[pos] = 0;
    return pos;
}

int LinuxNetBridge::pd(char* out, int pos, int mx, int val) {
    if (val == 0) { if (pos < mx - 1) out[pos++] = '0'; out[pos] = 0; return pos; }
    char tmp[12]; int i = 0;
    if (val < 0) { if (pos < mx - 1) out[pos++] = '-'; val = -val; }
    while (val > 0) { tmp[i++] = '0' + (val % 10); val /= 10; }
    for (int j = i - 1; j >= 0 && pos < mx - 1; j--) out[pos++] = tmp[j];
    out[pos] = 0;
    return pos;
}

static bool ln_seq(const char* a, const char* b) {
    while (*a && *b) { if (*a != *b) return false; a++; b++; }
    return *a == 0 && *b == 0;
}

static void ln_scpy(char* d, const char* s, int mx) {
    int i = 0;
    while (s && s[i] && i < mx - 1) { d[i] = s[i]; i++; }
    d[i] = 0;
}

static uint32_t ln_ip_to_u32(IPv4Address ip) {
    return ((uint32_t)ip.bytes[0] << 24) |
           ((uint32_t)ip.bytes[1] << 16) |
           ((uint32_t)ip.bytes[2] << 8) |
           (uint32_t)ip.bytes[3];
}

//  init

void LinuxNetBridge::Init() {
    memset(sockets, 0, sizeof(sockets));
    memset(interfaces, 0, sizeof(interfaces));
    socket_count = 0;
    iface_count = 0;

    InitInterfaces();

    SerialLogger::Log("[LinuxNet] Network bridge initialized (");
    SerialLogger::LogDec(iface_count);
    SerialLogger::Log(" interfaces)\r\n");
}

void LinuxNetBridge::InitInterfaces() {
    iface_count = 0;

    // lo  -  loopback
    LinuxNetInterface* lo = &interfaces[iface_count++];
    ln_scpy(lo->name, "lo", sizeof(lo->name));
    lo->ip_addr = 0x7F000001;     // 127.0.0.1
    lo->netmask = 0xFF000000;     // 255.0.0.0
    lo->gateway = 0;
    lo->broadcast = 0x7FFFFFFF;
    memset(lo->mac, 0, 6);
    lo->up = true;
    lo->loopback = true;
    lo->mtu = 65536;
    lo->rx_bytes = lo->tx_bytes = 0;
    lo->rx_packets = lo->tx_packets = 0;

    // eth0  -  primary interface (shared with kurono)
    LinuxNetInterface* eth = &interfaces[iface_count++];
    ln_scpy(eth->name, "eth0", sizeof(eth->name));
    NetworkInterface* kurono_eth = Network::GetInterface("eth0");
    if (kurono_eth) {
        eth->ip_addr = ln_ip_to_u32(kurono_eth->ip);
        eth->netmask = ln_ip_to_u32(kurono_eth->netmask);
        eth->gateway = ln_ip_to_u32(kurono_eth->gateway);
        eth->broadcast = eth->ip_addr | ~eth->netmask;
        for (int i = 0; i < 6; i++) eth->mac[i] = kurono_eth->mac.bytes[i];
        eth->up = kurono_eth->state == NIC_UP;
        dns_primary = ln_ip_to_u32(kurono_eth->dns);
        if (dns_primary == 0) dns_primary = TCPStack::MakeIP(8, 8, 8, 8);
        dns_secondary = dns_primary;
    } else {
        eth->ip_addr   = 0x0A00020F;  // 10.0.2.15
        eth->netmask   = 0xFFFFFF00;  // 255.255.255.0
        eth->gateway   = 0x0A000202;  // 10.0.2.2
        eth->broadcast = 0x0A0002FF;  // 10.0.2.255
        eth->mac[0] = 0x02; eth->mac[1] = 0x42;
        eth->mac[2] = 0xAC; eth->mac[3] = 0x11;
        eth->mac[4] = 0x00; eth->mac[5] = 0x02;
        eth->up = false;
    }
    eth->loopback = false;
    eth->mtu = 1500;
    eth->rx_bytes = 1024;
    eth->tx_bytes = 512;
    eth->rx_packets = 16;
    eth->tx_packets = 8;

    // write resolv.conf to reflect dns settings
    char resolv[256];
    int p = 0;
    p = pa(resolv, p, sizeof(resolv), "# Generated by Kurono Linux Network Bridge\n");
    p = pa(resolv, p, sizeof(resolv), "nameserver ");
    char ipbuf[16]; IpToStr(dns_primary, ipbuf, sizeof(ipbuf));
    p = pa(resolv, p, sizeof(resolv), ipbuf);
    p = pa(resolv, p, sizeof(resolv), "\nnameserver ");
    IpToStr(dns_secondary, ipbuf, sizeof(ipbuf));
    p = pa(resolv, p, sizeof(resolv), ipbuf);
    p = pa(resolv, p, sizeof(resolv), "\n");
    KVFS::WriteString("/etc/resolv.conf", resolv);
    KVFS::WriteString("/linux/etc/resolv.conf", resolv);
}

//  bsd socket api

int LinuxNetBridge::AllocSocket() {
    for (int i = 0; i < LNET_MAX_SOCKETS; i++) {
        if (!sockets[i].active) return i;
    }
    return -1;
}

LinuxSocket* LinuxNetBridge::GetSocket(int fd) {
    if (fd < 0 || fd >= LNET_MAX_SOCKETS) return nullptr;
    if (!sockets[fd].active) return nullptr;
    return &sockets[fd];
}

int LinuxNetBridge::Socket(int family, int type, int protocol, int owner_pid) {
    if (family != LAF_INET) return -97;                 // -EAFNOSUPPORT (satoru)
    if (type != LSOCK_STREAM && type != LSOCK_DGRAM) return -94;  // -ESOCKTNOSUPPORT (satoru)
    int idx = AllocSocket();
    if (idx < 0) return -24;                            // -EMFILE (satoru)

    int ks;
    {
        SpinLockCpuGuard g(g_net_lock);
        ks = TCPStack::Socket(type == LSOCK_STREAM ? SOCK_STREAM : SOCK_DGRAM);
        // ALWAYS non-blocking at the stack level: the bridge owns no waiting,
        // so TCPStack's internal PumpUI waits stay unreachable (ap-unsafe).
        // linux-level blocking is emulated in the syscall layer. (satoru)
        if (ks >= 0) TCPStack::SetNonblocking(ks, true);
    }
    if (ks < 0) return -24;                             // stack table full (satoru)

    LinuxSocket* s = &sockets[idx];
    memset(s, 0, sizeof(LinuxSocket));
    s->fd = idx;
    s->family = family;
    s->type = type;
    s->protocol = protocol;
    s->state = LSOCK_CREATED;
    s->active = true;
    s->owner_pid = owner_pid;
    s->kurono_socket = ks;
    s->nonblocking = true;
    s->refs = 1;

    socket_count++;
    return idx;
}

int LinuxNetBridge::Bind(int sockfd, const LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !addr) return -9;                         // -EBADF (satoru)

    s->local_addr = Ntohl(addr->sin_addr);
    s->local_port = Ntohs(addr->sin_port);
    // port 0 stays 0 here: TCPStack allocates an ephemeral port at the first
    // SendTo/Connect (musl's resolver binds 0.0.0.0:0 then sendto's). (satoru)
    if (s->local_port != 0) {
        SpinLockCpuGuard g(g_net_lock);
        TCPStack::Bind(s->kurono_socket, s->local_port);
    }
    s->state = LSOCK_BOUND;
    return 0;
}

int LinuxNetBridge::Listen(int sockfd, int backlog) {
    // v1: no inbound tcp  -  TCPStack::Accept blocks with PumpUI (ap-unsafe)
    // and nothing firefox needs listens. (satoru)
    (void)sockfd; (void)backlog;
    return -95;                                          // -EOPNOTSUPP (satoru)
}

int LinuxNetBridge::Accept(int sockfd, LinuxSockaddrIn* addr) {
    (void)sockfd; (void)addr;
    return -95;                                          // -EOPNOTSUPP (satoru)
}

int LinuxNetBridge::Connect(int sockfd, const LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !addr) return -9;
    if (s->state == LSOCK_CONNECTING) return -114;       // -EALREADY (satoru)
    if (s->state == LSOCK_CONNECTED && s->type == LSOCK_STREAM) return -106;  // -EISCONN (satoru)

    uint32_t ip   = Ntohl(addr->sin_addr);
    uint16_t port = Ntohs(addr->sin_port);

    // no loopback in the kurono stack: fast-fail so a 127.0.0.1 probe reads
    // as refused instead of hanging firefox startup. (satoru)
    if ((ip >> 24) == 127 || ip == 0) return -111;       // -ECONNREFUSED (satoru)

    s->remote_addr = ip;
    s->remote_port = port;

    if (s->type == LSOCK_DGRAM) {
        // connected-udp just fixes the default destination. (satoru)
        s->state = LSOCK_CONNECTED;
        return 0;
    }

    bool ok;
    {
        SpinLockCpuGuard g(g_net_lock);
        ok = TCPStack::Connect(s->kurono_socket, ip, port);
    }
    if (ok) { s->state = LSOCK_CONNECTED; return 0; }    // same-tick establish (satoru)
    // non-blocking connect: SYN is out, handshake completes from the network
    // tick. the caller polls (POLLOUT) + getsockopt(SO_ERROR). (satoru)
    if (TCPStack::GetSockError(s->kurono_socket) == TCP_EINPROGRESS) {
        s->state = LSOCK_CONNECTING;
        return -115;                                     // -EINPROGRESS (satoru)
    }
    return -111;                                         // -ECONNREFUSED (satoru)
}

// sample a connecting socket's state without blocking: 0 once established,
// -EINPROGRESS while the handshake runs, else the connect error. transitions
// the bridge state so later Send/Recv see CONNECTED. (satoru)
int LinuxNetBridge::ConnectPoll(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -9;
    if (s->state == LSOCK_CONNECTED) return 0;
    if (s->state != LSOCK_CONNECTING) return -107;       // -ENOTCONN (satoru)
    if (TCPStack::IsWritable(s->kurono_socket)) {
        s->state = LSOCK_CONNECTED;
        return 0;
    }
    int e = TCPStack::GetSockError(s->kurono_socket);
    if (e == TCP_EINPROGRESS || e == 0) return -115;     // still handshaking (satoru)
    s->state = LSOCK_CLOSED;
    return -e;                                           // -ECONNREFUSED / -ETIMEDOUT (satoru)
}

int LinuxNetBridge::Send(int sockfd, const void* buf, int len, int flags) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !buf || len < 0) return -9;
    (void)flags;

    if (s->type == LSOCK_DGRAM) {
        // connected-udp send: bridge-stored remote, never NetSocket state
        // (ProcessUDP clobbers remote_* per received packet). (satoru)
        if (s->state != LSOCK_CONNECTED) return -107;    // -ENOTCONN (satoru)
        if (len > 1472) return -90;                      // -EMSGSIZE (satoru)
        int w;
        {
            SpinLockCpuGuard g(g_net_lock);
            w = TCPStack::SendTo(s->kurono_socket, buf, len, s->remote_addr, s->remote_port);
        }
        return w < 0 ? -11 : w;                          // -EAGAIN on stack refusal (satoru)
    }

    // tcp. late-complete a pending connect (caller may skip ConnectPoll and
    // go straight to write after its poll saw POLLOUT). (satoru)
    if (s->state == LSOCK_CONNECTING) {
        if (TCPStack::IsWritable(s->kurono_socket)) s->state = LSOCK_CONNECTED;
        else return -107;                                // -ENOTCONN (satoru)
    }
    if (s->state != LSOCK_CONNECTED) return -107;
    if (TCPStack::IsPeerClosed(s->kurono_socket)) return -32;   // -EPIPE (satoru)

    // pre-check the send window so TCPStack::Send can NEVER enter its
    // internal window-full PumpUI wait  -  short writes are fine, callers
    // loop. (satoru)
    int free_segs = TCPStack::TxFreeSegs(s->kurono_socket);
    if (free_segs <= 0) return -11;                      // -EAGAIN (satoru)
    int chunk = free_segs * TCP_MSS;
    if (chunk > len) chunk = len;

    int w;
    {
        SpinLockCpuGuard g(g_net_lock);
        w = TCPStack::Send(s->kurono_socket, buf, chunk);
    }
    if (w < 0) return -11;
    LinuxNetInterface* eth = GetInterface("eth0");
    if (eth) { eth->tx_bytes += w; eth->tx_packets++; }
    return w;
}

int LinuxNetBridge::Recv(int sockfd, void* buf, int len, int flags) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !buf || len < 0) return -9;
    (void)flags;

    if (s->type == LSOCK_DGRAM) {
        return Recvfrom(sockfd, buf, len, 0, nullptr);
    }

    if (s->state == LSOCK_CONNECTING) {
        if (TCPStack::IsWritable(s->kurono_socket)) s->state = LSOCK_CONNECTED;
        else return -107;                                // -ENOTCONN (satoru)
    }

    // 0-vs-EAGAIN: an empty ring is EOF only once the peer is gone; getting
    // this wrong reads as instant-eof (broken pages) or a spin (hung
    // transfers). (satoru)
    if (TCPStack::RxAvailable(s->kurono_socket) == 0) {
        if (TCPStack::IsPeerClosed(s->kurono_socket)) return 0;   // eof (satoru)
        return -11;                                      // -EAGAIN (satoru)
    }

    int r;
    {
        SpinLockCpuGuard g(g_net_lock);
        // Recv mutates state (window-update acks)  -  locked. (satoru)
        r = TCPStack::Recv(s->kurono_socket, buf, len);
    }
    if (r < 0) return -11;
    if (r == 0) return -11;                              // raced empty (satoru)
    LinuxNetInterface* eth = GetInterface("eth0");
    if (eth) { eth->rx_bytes += r; eth->rx_packets++; }
    return r;
}

int LinuxNetBridge::Sendto(int sockfd, const void* buf, int len, int flags,
                            const LinuxSockaddrIn* dest_addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !buf || len < 0) return -9;
    (void)flags;

    // null dest = connected-mode send. (satoru)
    if (!dest_addr) return Send(sockfd, buf, len, 0);
    if (s->type != LSOCK_DGRAM) return Send(sockfd, buf, len, 0);
    if (len > 1472) return -90;                          // -EMSGSIZE (satoru)

    uint32_t ip   = Ntohl(dest_addr->sin_addr);
    uint16_t port = Ntohs(dest_addr->sin_port);
    int w;
    {
        SpinLockCpuGuard g(g_net_lock);
        w = TCPStack::SendTo(s->kurono_socket, buf, len, ip, port);
    }
    if (w < 0) return -11;
    LinuxNetInterface* eth = GetInterface("eth0");
    if (eth) { eth->tx_bytes += w; eth->tx_packets++; }
    return w;
}

int LinuxNetBridge::Recvfrom(int sockfd, void* buf, int len, int flags,
                              LinuxSockaddrIn* src_addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !buf || len < 0) return -9;
    (void)flags;

    if (s->type != LSOCK_DGRAM) return Recv(sockfd, buf, len, 0);

    if (TCPStack::RxAvailable(s->kurono_socket) == 0) return -11;  // -EAGAIN (satoru)

    uint32_t fip = 0; uint16_t fport = 0;
    int r;
    {
        SpinLockCpuGuard g(g_net_lock);
        // pops exactly one framed datagram record (true per-datagram source  - 
        // musl's resolver memcmps it). (satoru)
        r = TCPStack::RecvFrom(s->kurono_socket, buf, len, &fip, &fport);
    }
    if (r < 0) return -11;
    if (r == 0) return -11;                              // raced empty (satoru)
    if (src_addr) {
        src_addr->sin_family = LAF_INET;
        src_addr->sin_addr = Htonl(fip);
        src_addr->sin_port = Htons(fport);
        memset(src_addr->sin_zero, 0, sizeof(src_addr->sin_zero));
    }
    return r;
}

int LinuxNetBridge::Shutdown(int sockfd, int how) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -9;
    // shut_wr / shut_rdwr sends fin via Close; shut_rd is a benign no-op
    // (the rx ring keeps draining). the linux fd stays open either way  - 
    // sys_close does the final release. (satoru)
    if (how == LSHUT_WR || how == LSHUT_RDWR) {
        if (s->type == LSOCK_STREAM && s->kurono_socket >= 0) {
            SpinLockCpuGuard g(g_net_lock);
            TCPStack::Close(s->kurono_socket);
        }
        s->state = LSOCK_CLOSED;
    }
    return 0;
}

int LinuxNetBridge::Close(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -9;
    // dup/fork refcount: only the LAST linux fd release tears down the
    // kurono socket  -  the 16-slot stack table makes leak discipline
    // critical. (satoru)
    if (--s->refs > 0) return 0;
    if (s->kurono_socket >= 0) {
        SpinLockCpuGuard g(g_net_lock);
        TCPStack::Close(s->kurono_socket);
    }
    s->kurono_socket = -1;
    s->active = false;
    s->state = LSOCK_CLOSED;
    socket_count--;
    return 0;
}

void LinuxNetBridge::Retain(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (s) s->refs++;
}

// poll/epoll readiness  -  lock-free single-word reads (same precedent as
// UnixSocket::PendingBytes in fd_readiness); staleness is bounded by the
// caller's next poll pass. (satoru)
uint32_t LinuxNetBridge::Readiness(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return LNET_POLLERR | LNET_POLLHUP;

    uint32_t r = 0;
    int ks = s->kurono_socket;
    if (s->type == LSOCK_DGRAM) {
        if (TCPStack::RxAvailable(ks) > 0) r |= LNET_POLLIN;
        r |= LNET_POLLOUT;                               // udp never queues (satoru)
        return r;
    }
    // tcp: readable on data OR peer-gone (recv returns eof); writable once
    // established with window space; err/hup on a failed connect so the
    // poll(POLLOUT) connect pattern wakes and reads SO_ERROR. (satoru)
    if (TCPStack::RxAvailable(ks) > 0) r |= LNET_POLLIN;
    bool peer_closed = TCPStack::IsPeerClosed(ks);
    if (peer_closed && s->state != LSOCK_CREATED && s->state != LSOCK_BOUND) {
        r |= LNET_POLLIN | LNET_POLLHUP;
    }
    if (TCPStack::IsWritable(ks) && TCPStack::TxFreeSegs(ks) > 0) r |= LNET_POLLOUT;
    int e = TCPStack::GetSockError(ks);
    if (e != 0 && e != TCP_EINPROGRESS) r |= LNET_POLLERR | LNET_POLLHUP;
    return r;
}

// getsockopt(SO_ERROR): pending connect error, 0 when fine. v1 keeps the
// error sticky (no clear-on-read)  -  firefox reads it once then closes the
// fd, so the simplification never bites. (satoru)
int LinuxNetBridge::SockError(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return 9;                                    // EBADF as a value (satoru)
    int e = TCPStack::GetSockError(s->kurono_socket);
    if (e == TCP_EINPROGRESS) return 0;                  // still in progress = no error (satoru)
    return e;
}

int LinuxNetBridge::RxAvail(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return 0;
    return TCPStack::RxAvailable(s->kurono_socket);
}

// rate-limited network pump for the bsp's poll/epoll wait loops: beats the
// NetworkProcess's 10ms cadence during dns/handshake/tls bursts. no-ops
// when no inet socket is live so non-network workloads pay nothing. (satoru)
void LinuxNetBridge::PumpTick() {
    if (socket_count <= 0) return;
    static uint32_t last_ms = 0;
    uint32_t now = Timer::GetRealMs();
    if (now - last_ms < 1) return;
    last_ms = now;
    SpinLockCpuGuard g(g_net_lock);
    TCPStack::Tick();
}

int LinuxNetBridge::Setsockopt(int sockfd, int level, int optname,
                                const void* optval, int optlen) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    (void)optlen;

    if (level == LSOL_SOCKET) {
        int val = optval ? *(const int*)optval : 0;
        switch (optname) {
            case LSO_REUSEADDR: s->reuse_addr = val != 0; break;
            case LSO_KEEPALIVE: s->keepalive = val != 0; break;
        }
    }
    return 0;
}

int LinuxNetBridge::Getsockopt(int sockfd, int level, int optname,
                                void* optval, int* optlen) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;

    if (level == LSOL_SOCKET && optval && optlen) {
        int* val = (int*)optval;
        switch (optname) {
            case LSO_REUSEADDR: *val = s->reuse_addr ? 1 : 0; break;
            case LSO_KEEPALIVE: *val = s->keepalive ? 1 : 0; break;
            default: *val = 0;
        }
        *optlen = sizeof(int);
    }
    return 0;
}

int LinuxNetBridge::Fcntl(int sockfd, int cmd, int arg) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    switch (cmd) {
        case LF_GETFL:
            return s->nonblocking ? LFD_O_NONBLOCK : 0;
        case LF_SETFL:
            // mirror the O_NONBLOCK bit; map the same flag onto the kurono
            // socket if this bridge socket is backed by one (satoru)
            s->nonblocking = (arg & LFD_O_NONBLOCK) != 0;
            if (s->kurono_socket >= 0)
                TCPStack::SetNonblocking(s->kurono_socket, s->nonblocking);
            return 0;
        default:
            return 0;
    }
}

bool LinuxNetBridge::IsNonblocking(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    return s && s->nonblocking;
}

int LinuxNetBridge::Getpeername(int sockfd, LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_CONNECTED || !addr) return -1;
    addr->sin_family = LAF_INET;
    addr->sin_addr = Htonl(s->remote_addr);
    addr->sin_port = Htons(s->remote_port);
    return 0;
}

int LinuxNetBridge::Getsockname(int sockfd, LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !addr) return -1;
    addr->sin_family = LAF_INET;
    addr->sin_addr = Htonl(s->local_addr);
    addr->sin_port = Htons(s->local_port);
    return 0;
}

//  network interfaces

LinuxNetInterface* LinuxNetBridge::GetInterface(const char* name) {
    for (int i = 0; i < iface_count; i++) {
        if (ln_seq(interfaces[i].name, name)) return &interfaces[i];
    }
    return nullptr;
}

LinuxNetInterface* LinuxNetBridge::GetInterfaces() { return interfaces; }
int LinuxNetBridge::GetInterfaceCount() { return iface_count; }

void LinuxNetBridge::SetInterfaceIP(const char* name, uint32_t ip, uint32_t mask) {
    LinuxNetInterface* iface = GetInterface(name);
    if (iface) { iface->ip_addr = ip; iface->netmask = mask; }
}

void LinuxNetBridge::SetInterfaceUp(const char* name, bool up) {
    LinuxNetInterface* iface = GetInterface(name);
    if (iface) iface->up = up;
}

//  dns

int LinuxNetBridge::Resolve(const char* hostname, uint32_t* ip_out) {
    if (!hostname || !ip_out) return -1;

    // built-in resolution
    if (ln_seq(hostname, "localhost")) { *ip_out = 0x7F000001; return 0; }
    if (ln_seq(hostname, "kurono"))    { *ip_out = 0x7F000001; return 0; }

    // real dns via the kernel resolver (bsp-only shell path  -  it pumps ui
    // internally). the old body returned a hardcoded fake ip. (satoru)
    IPv4Address r;
    if (Network::Resolve(hostname, &r)) { *ip_out = ln_ip_to_u32(r); return 0; }
    return -1;
}

void LinuxNetBridge::SetDNS(uint32_t primary, uint32_t secondary) {
    dns_primary = primary;
    dns_secondary = secondary;
}

void LinuxNetBridge::GetDNS(uint32_t* primary, uint32_t* secondary) {
    if (primary) *primary = dns_primary;
    if (secondary) *secondary = dns_secondary;
}

//  byte order

uint16_t LinuxNetBridge::Htons(uint16_t v) {
    return (v >> 8) | (v << 8);
}

uint16_t LinuxNetBridge::Ntohs(uint16_t v) {
    return Htons(v);
}

uint32_t LinuxNetBridge::Htonl(uint32_t v) {
    return ((v >> 24) & 0xFF) | ((v >> 8) & 0xFF00) |
           ((v << 8) & 0xFF0000) | ((v << 24) & 0xFF000000);
}

uint32_t LinuxNetBridge::Ntohl(uint32_t v) {
    return Htonl(v);
}

void LinuxNetBridge::IpToStr(uint32_t ip, char* buf, int max) {
    int p = 0;
    for (int i = 3; i >= 0; i--) {
        int octet = (ip >> (i * 8)) & 0xFF;
        if (octet >= 100) { if (p < max - 1) buf[p++] = '0' + (octet / 100); }
        if (octet >= 10)  { if (p < max - 1) buf[p++] = '0' + ((octet / 10) % 10); }
        if (p < max - 1) buf[p++] = '0' + (octet % 10);
        if (i > 0 && p < max - 1) buf[p++] = '.';
    }
    buf[p] = 0;
}

//  output formatters

void LinuxNetBridge::Ifconfig(char* out, int max_out) {
    int p = 0;
    char ipbuf[16];

    for (int i = 0; i < iface_count; i++) {
        LinuxNetInterface* iface = &interfaces[i];

        p = pa(out, p, max_out, iface->name);
        p = pa(out, p, max_out, ": flags=");
        p = pd(out, p, max_out, iface->up ? 4163 : 0);
        p = pa(out, p, max_out, "<");
        if (iface->up) p = pa(out, p, max_out, "UP,");
        if (iface->loopback) p = pa(out, p, max_out, "LOOPBACK,");
        else p = pa(out, p, max_out, "BROADCAST,");
        p = pa(out, p, max_out, "RUNNING,MULTICAST>  mtu ");
        p = pd(out, p, max_out, iface->mtu);
        p = pa(out, p, max_out, "\n");

        p = pa(out, p, max_out, "        inet ");
        IpToStr(iface->ip_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf);
        p = pa(out, p, max_out, "  netmask ");
        IpToStr(iface->netmask, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf);
        if (!iface->loopback) {
            p = pa(out, p, max_out, "  broadcast ");
            IpToStr(iface->broadcast, ipbuf, sizeof(ipbuf));
            p = pa(out, p, max_out, ipbuf);
        }
        p = pa(out, p, max_out, "\n");

        if (!iface->loopback) {
            p = pa(out, p, max_out, "        ether ");
            for (int j = 0; j < 6; j++) {
                const char* hex = "0123456789abcdef";
                if (p < max_out - 1) out[p++] = hex[iface->mac[j] >> 4];
                if (p < max_out - 1) out[p++] = hex[iface->mac[j] & 0xF];
                if (j < 5 && p < max_out - 1) out[p++] = ':';
            }
            p = pa(out, p, max_out, "\n");
        }

        p = pa(out, p, max_out, "        RX packets ");
        p = pd(out, p, max_out, (int)iface->rx_packets);
        p = pa(out, p, max_out, "  bytes ");
        p = pd(out, p, max_out, (int)iface->rx_bytes);
        p = pa(out, p, max_out, "\n        TX packets ");
        p = pd(out, p, max_out, (int)iface->tx_packets);
        p = pa(out, p, max_out, "  bytes ");
        p = pd(out, p, max_out, (int)iface->tx_bytes);
        p = pa(out, p, max_out, "\n\n");
    }
    out[p] = 0;
}

void LinuxNetBridge::IpAddr(char* out, int max_out) {
    Ifconfig(out, max_out);  // same output format for now
}

void LinuxNetBridge::Netstat(char* out, int max_out) {
    int p = 0;
    p = pa(out, p, max_out, "Active Internet connections\n");
    p = pa(out, p, max_out, "Proto Recv-Q Send-Q Local Address        Foreign Address      State\n");

    char ipbuf[16];
    for (int i = 0; i < LNET_MAX_SOCKETS; i++) {
        if (!sockets[i].active) continue;
        LinuxSocket* s = &sockets[i];

        p = pa(out, p, max_out, s->type == LSOCK_STREAM ? "tcp   " : "udp   ");
        p = pd(out, p, max_out, s->recv_len); p = pa(out, p, max_out, "      ");
        p = pd(out, p, max_out, s->send_len); p = pa(out, p, max_out, "      ");

        IpToStr(s->local_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf); p = pa(out, p, max_out, ":");
        p = pd(out, p, max_out, s->local_port);

        p = pa(out, p, max_out, "   ");
        IpToStr(s->remote_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf); p = pa(out, p, max_out, ":");
        p = pd(out, p, max_out, s->remote_port);

        const char* st;
        switch (s->state) {
            case LSOCK_CLOSED:     st = "CLOSED"; break;
            case LSOCK_CREATED:    st = "CREATED"; break;
            case LSOCK_BOUND:      st = "BOUND"; break;
            case LSOCK_LISTENING:  st = "LISTEN"; break;
            case LSOCK_CONNECTED:  st = "ESTABLISHED"; break;
            case LSOCK_CONNECTING: st = "SYN_SENT"; break;
            default: st = "???"; break;
        }
        p = pa(out, p, max_out, "   ");
        p = pa(out, p, max_out, st);
        p = pa(out, p, max_out, "\n");
    }
    out[p] = 0;
}

//  shell commands

void LinuxNetBridge::RegisterShellCommands(void* shell) {
    Shell* sh = (Shell*)shell;
    if (!sh) return;
    sh->RegisterCommand("ifconfig_l", cmd_ifconfig, "Linux network interface config");
    sh->RegisterCommand("ip_l",       cmd_ip,       "Linux IP configuration");
    sh->RegisterCommand("netstat_l",  cmd_netstat,  "Linux network connections");
    sh->RegisterCommand("ping_l",     cmd_ping,     "Linux ping");
    sh->RegisterCommand("nslookup",   cmd_nslookup, "DNS lookup");
}

int LinuxNetBridge::cmd_ifconfig(void*, int, const char**, char* out, int mx) {
    Ifconfig(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_ip(void*, int, const char**, char* out, int mx) {
    IpAddr(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_netstat(void*, int, const char**, char* out, int mx) {
    Netstat(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_ping(void*, int argc, const char** argv, char* out, int mx) {
    int p = 0;
    if (argc < 2) {
        return pa(out, 0, mx, "Usage: ping <hostname|ip>\n");
    }

    const char* host = argv[1];
    uint32_t ip;
    Resolve(host, &ip);

    char ipbuf[16];
    IpToStr(ip, ipbuf, sizeof(ipbuf));

    p = pa(out, p, mx, "PING ");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, " (");
    p = pa(out, p, mx, ipbuf);
    p = pa(out, p, mx, ") 56(84) bytes of data.\n");

    for (int i = 0; i < 4; i++) {
        p = pa(out, p, mx, "64 bytes from ");
        p = pa(out, p, mx, ipbuf);
        p = pa(out, p, mx, ": icmp_seq=");
        p = pd(out, p, mx, i + 1);
        p = pa(out, p, mx, " ttl=64 time=0.");
        p = pd(out, p, mx, 1 + i);
        p = pa(out, p, mx, " ms\n");
    }

    p = pa(out, p, mx, "\n--- ");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, " ping statistics ---\n");
    p = pa(out, p, mx, "4 packets transmitted, 4 received, 0% packet loss\n");
    p = pa(out, p, mx, "rtt min/avg/max/mdev = 0.1/0.2/0.4/0.1 ms\n");
    return p;
}

int LinuxNetBridge::cmd_nslookup(void*, int argc, const char** argv, char* out, int mx) {
    int p = 0;
    if (argc < 2) {
        return pa(out, 0, mx, "Usage: nslookup <hostname>\n");
    }

    const char* host = argv[1];
    uint32_t ip;
    Resolve(host, &ip);

    char ipbuf[16];
    IpToStr(ip, ipbuf, sizeof(ipbuf));
    char dns_buf[16];
    IpToStr(dns_primary, dns_buf, sizeof(dns_buf));

    p = pa(out, p, mx, "Server:\t\t");
    p = pa(out, p, mx, dns_buf);
    p = pa(out, p, mx, "\nAddress:\t");
    p = pa(out, p, mx, dns_buf);
    p = pa(out, p, mx, "#53\n\nNon-authoritative answer:\n");
    p = pa(out, p, mx, "Name:\t");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, "\nAddress: ");
    p = pa(out, p, mx, ipbuf);
    p = pa(out, p, mx, "\n");
    return p;
}
