//  kurono os  -  linux network stack bridge  -  implementation

#include "linux_netbridge.h"
#include "../kernel/heap.h"
#include "../drivers/serial.h"
#include "../fs/kvfs.h"
#include "../net/network.h"
#include "../net/tcpip.h"
#include "../shell/shell.h"

LinuxSocket       LinuxNetBridge::sockets[LNET_MAX_SOCKETS];
int               LinuxNetBridge::socket_count = 0;
LinuxNetInterface LinuxNetBridge::interfaces[LNET_MAX_INTERFACES];
int               LinuxNetBridge::iface_count = 0;
uint32_t          LinuxNetBridge::dns_primary = 0x08080808;   // 8.8.8.8
uint32_t          LinuxNetBridge::dns_secondary = 0x08080404; // 8.8.4.4

int LinuxNetBridge::pa(char* out, int pos, int mx, const char* s) {
    while (*s && pos < mx - 1) out[pos++] = *s++;
    out[pos] = 0;
    return pos;
}

int LinuxNetBridge::pd(char* out, int pos, int mx, int val) {
    if (val == 0) { if (pos < mx - 1) out[pos++] = '0'; out[pos] = 0; return pos; }
    char tmp[12]; int i = 0;
    if (val < 0) { if (pos < mx - 1) out[pos++] = '-'; val = -val; }
    while (val > 0) { tmp[i++] = '0' + (val % 10); val /= 10; }
    for (int j = i - 1; j >= 0 && pos < mx - 1; j--) out[pos++] = tmp[j];
    out[pos] = 0;
    return pos;
}

static bool ln_seq(const char* a, const char* b) {
    while (*a && *b) { if (*a != *b) return false; a++; b++; }
    return *a == 0 && *b == 0;
}

static void ln_scpy(char* d, const char* s, int mx) {
    int i = 0;
    while (s && s[i] && i < mx - 1) { d[i] = s[i]; i++; }
    d[i] = 0;
}

static uint32_t ln_ip_to_u32(IPv4Address ip) {
    return ((uint32_t)ip.bytes[0] << 24) |
           ((uint32_t)ip.bytes[1] << 16) |
           ((uint32_t)ip.bytes[2] << 8) |
           (uint32_t)ip.bytes[3];
}

//  init

void LinuxNetBridge::Init() {
    memset(sockets, 0, sizeof(sockets));
    memset(interfaces, 0, sizeof(interfaces));
    socket_count = 0;
    iface_count = 0;

    InitInterfaces();

    SerialLogger::Log("[LinuxNet] Network bridge initialized (");
    SerialLogger::LogDec(iface_count);
    SerialLogger::Log(" interfaces)\r\n");
}

void LinuxNetBridge::InitInterfaces() {
    iface_count = 0;

    // lo  -  loopback
    LinuxNetInterface* lo = &interfaces[iface_count++];
    ln_scpy(lo->name, "lo", sizeof(lo->name));
    lo->ip_addr = 0x7F000001;     // 127.0.0.1
    lo->netmask = 0xFF000000;     // 255.0.0.0
    lo->gateway = 0;
    lo->broadcast = 0x7FFFFFFF;
    memset(lo->mac, 0, 6);
    lo->up = true;
    lo->loopback = true;
    lo->mtu = 65536;
    lo->rx_bytes = lo->tx_bytes = 0;
    lo->rx_packets = lo->tx_packets = 0;

    // eth0  -  primary interface (shared with kurono)
    LinuxNetInterface* eth = &interfaces[iface_count++];
    ln_scpy(eth->name, "eth0", sizeof(eth->name));
    NetworkInterface* kurono_eth = Network::GetInterface("eth0");
    if (kurono_eth) {
        eth->ip_addr = ln_ip_to_u32(kurono_eth->ip);
        eth->netmask = ln_ip_to_u32(kurono_eth->netmask);
        eth->gateway = ln_ip_to_u32(kurono_eth->gateway);
        eth->broadcast = eth->ip_addr | ~eth->netmask;
        for (int i = 0; i < 6; i++) eth->mac[i] = kurono_eth->mac.bytes[i];
        eth->up = kurono_eth->state == NIC_UP;
        dns_primary = ln_ip_to_u32(kurono_eth->dns);
        if (dns_primary == 0) dns_primary = TCPStack::MakeIP(8, 8, 8, 8);
        dns_secondary = dns_primary;
    } else {
        eth->ip_addr   = 0x0A00020F;  // 10.0.2.15
        eth->netmask   = 0xFFFFFF00;  // 255.255.255.0
        eth->gateway   = 0x0A000202;  // 10.0.2.2
        eth->broadcast = 0x0A0002FF;  // 10.0.2.255
        eth->mac[0] = 0x02; eth->mac[1] = 0x42;
        eth->mac[2] = 0xAC; eth->mac[3] = 0x11;
        eth->mac[4] = 0x00; eth->mac[5] = 0x02;
        eth->up = false;
    }
    eth->loopback = false;
    eth->mtu = 1500;
    eth->rx_bytes = 1024;
    eth->tx_bytes = 512;
    eth->rx_packets = 16;
    eth->tx_packets = 8;

    // write resolv.conf to reflect dns settings
    char resolv[256];
    int p = 0;
    p = pa(resolv, p, sizeof(resolv), "# Generated by Kurono Linux Network Bridge\n");
    p = pa(resolv, p, sizeof(resolv), "nameserver ");
    char ipbuf[16]; IpToStr(dns_primary, ipbuf, sizeof(ipbuf));
    p = pa(resolv, p, sizeof(resolv), ipbuf);
    p = pa(resolv, p, sizeof(resolv), "\nnameserver ");
    IpToStr(dns_secondary, ipbuf, sizeof(ipbuf));
    p = pa(resolv, p, sizeof(resolv), ipbuf);
    p = pa(resolv, p, sizeof(resolv), "\n");
    KVFS::WriteString("/etc/resolv.conf", resolv);
    KVFS::WriteString("/linux/etc/resolv.conf", resolv);
}

//  bsd socket api

int LinuxNetBridge::AllocSocket() {
    for (int i = 0; i < LNET_MAX_SOCKETS; i++) {
        if (!sockets[i].active) return i;
    }
    return -1;
}

LinuxSocket* LinuxNetBridge::GetSocket(int fd) {
    if (fd < 0 || fd >= LNET_MAX_SOCKETS) return nullptr;
    if (!sockets[fd].active) return nullptr;
    return &sockets[fd];
}

int LinuxNetBridge::Socket(int family, int type, int protocol, int owner_pid) {
    int idx = AllocSocket();
    if (idx < 0) return -1;

    LinuxSocket* s = &sockets[idx];
    memset(s, 0, sizeof(LinuxSocket));
    s->fd = idx;
    s->family = family;
    s->type = type;
    s->protocol = protocol;
    s->state = LSOCK_CREATED;
    s->active = true;
    s->owner_pid = owner_pid;
    s->kurono_socket = -1;

    socket_count++;
    return idx;
}

int LinuxNetBridge::Bind(int sockfd, const LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;

    s->local_addr = Ntohl(addr->sin_addr);
    s->local_port = Ntohs(addr->sin_port);
    s->state = LSOCK_BOUND;
    return 0;
}

int LinuxNetBridge::Listen(int sockfd, int backlog) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_BOUND) return -1;

    s->backlog = backlog > LNET_MAX_BACKLOG ? LNET_MAX_BACKLOG : backlog;
    s->state = LSOCK_LISTENING;
    return 0;
}

int LinuxNetBridge::Accept(int sockfd, LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_LISTENING) return -1;

    // create new socket for the accepted connection
    int new_fd = Socket(s->family, s->type, s->protocol, s->owner_pid);
    if (new_fd < 0) return -1;

    LinuxSocket* ns = &sockets[new_fd];
    ns->state = LSOCK_CONNECTED;
    ns->local_addr = s->local_addr;
    ns->local_port = s->local_port;
    ns->remote_addr = 0xC0A80001;  // simulated remote
    ns->remote_port = 12345;

    if (addr) {
        addr->sin_family = LAF_INET;
        addr->sin_addr = Htonl(ns->remote_addr);
        addr->sin_port = Htons(ns->remote_port);
    }

    return new_fd;
}

int LinuxNetBridge::Connect(int sockfd, const LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;

    s->remote_addr = Ntohl(addr->sin_addr);
    s->remote_port = Ntohs(addr->sin_port);

    // if not bound, auto-bind
    if (s->local_port == 0) {
        s->local_addr = 0xC0A80064;  // 192.168.0.100
        s->local_port = 49152 + sockfd;
    }

    // honour O_NONBLOCK: report the handshake as in-progress and return
    // -EINPROGRESS, matching BSD semantics; blocking connect stays the
    // default and immediately reports CONNECTED as before (satoru)
    if (s->nonblocking) {
        s->state = LSOCK_CONNECTING;
        return -115;  // -EINPROGRESS
    }

    s->state = LSOCK_CONNECTED;
    return 0;
}

int LinuxNetBridge::Send(int sockfd, const void* buf, int len, int flags) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_CONNECTED) return -1;
    (void)flags;

    // buffer the data
    int copy = len < (LNET_BUF_SIZE - s->send_len) ? len : (LNET_BUF_SIZE - s->send_len);
    if (copy > 0) {
        memcpy(s->send_buf + s->send_len, buf, copy);
        s->send_len += copy;
    }

    // update interface stats
    LinuxNetInterface* eth = GetInterface("eth0");
    if (eth) {
        eth->tx_bytes += copy;
        eth->tx_packets++;
    }

    return copy;
}

int LinuxNetBridge::Recv(int sockfd, void* buf, int len, int flags) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_CONNECTED) return -1;
    (void)flags;

    int copy = len < s->recv_len ? len : s->recv_len;
    if (copy > 0) {
        memcpy(buf, s->recv_buf, copy);
        // shift remaining
        memmove(s->recv_buf, s->recv_buf + copy, s->recv_len - copy);
        s->recv_len -= copy;
    }

    return copy;
}

int LinuxNetBridge::Sendto(int sockfd, const void* buf, int len, int flags,
                            const LinuxSockaddrIn* dest_addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    (void)flags; (void)dest_addr;

    int copy = len < LNET_BUF_SIZE ? len : LNET_BUF_SIZE;
    memcpy(s->send_buf, buf, copy);
    s->send_len = copy;

    LinuxNetInterface* eth = GetInterface("eth0");
    if (eth) { eth->tx_bytes += copy; eth->tx_packets++; }

    return copy;
}

int LinuxNetBridge::Recvfrom(int sockfd, void* buf, int len, int flags,
                              LinuxSockaddrIn* src_addr) {
    (void)flags; (void)src_addr;
    return Recv(sockfd, buf, len, 0);
}

int LinuxNetBridge::Shutdown(int sockfd, int how) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    (void)how;
    s->state = LSOCK_CLOSED;
    return 0;
}

int LinuxNetBridge::Close(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    s->active = false;
    s->state = LSOCK_CLOSED;
    socket_count--;
    return 0;
}

int LinuxNetBridge::Setsockopt(int sockfd, int level, int optname,
                                const void* optval, int optlen) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    (void)optlen;

    if (level == LSOL_SOCKET) {
        int val = optval ? *(const int*)optval : 0;
        switch (optname) {
            case LSO_REUSEADDR: s->reuse_addr = val != 0; break;
            case LSO_KEEPALIVE: s->keepalive = val != 0; break;
        }
    }
    return 0;
}

int LinuxNetBridge::Getsockopt(int sockfd, int level, int optname,
                                void* optval, int* optlen) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;

    if (level == LSOL_SOCKET && optval && optlen) {
        int* val = (int*)optval;
        switch (optname) {
            case LSO_REUSEADDR: *val = s->reuse_addr ? 1 : 0; break;
            case LSO_KEEPALIVE: *val = s->keepalive ? 1 : 0; break;
            default: *val = 0;
        }
        *optlen = sizeof(int);
    }
    return 0;
}

int LinuxNetBridge::Fcntl(int sockfd, int cmd, int arg) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s) return -1;
    switch (cmd) {
        case LF_GETFL:
            return s->nonblocking ? LFD_O_NONBLOCK : 0;
        case LF_SETFL:
            // mirror the O_NONBLOCK bit; map the same flag onto the kurono
            // socket if this bridge socket is backed by one (satoru)
            s->nonblocking = (arg & LFD_O_NONBLOCK) != 0;
            if (s->kurono_socket >= 0)
                TCPStack::SetNonblocking(s->kurono_socket, s->nonblocking);
            return 0;
        default:
            return 0;
    }
}

bool LinuxNetBridge::IsNonblocking(int sockfd) {
    LinuxSocket* s = GetSocket(sockfd);
    return s && s->nonblocking;
}

int LinuxNetBridge::Getpeername(int sockfd, LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || s->state != LSOCK_CONNECTED || !addr) return -1;
    addr->sin_family = LAF_INET;
    addr->sin_addr = Htonl(s->remote_addr);
    addr->sin_port = Htons(s->remote_port);
    return 0;
}

int LinuxNetBridge::Getsockname(int sockfd, LinuxSockaddrIn* addr) {
    LinuxSocket* s = GetSocket(sockfd);
    if (!s || !addr) return -1;
    addr->sin_family = LAF_INET;
    addr->sin_addr = Htonl(s->local_addr);
    addr->sin_port = Htons(s->local_port);
    return 0;
}

//  network interfaces

LinuxNetInterface* LinuxNetBridge::GetInterface(const char* name) {
    for (int i = 0; i < iface_count; i++) {
        if (ln_seq(interfaces[i].name, name)) return &interfaces[i];
    }
    return nullptr;
}

LinuxNetInterface* LinuxNetBridge::GetInterfaces() { return interfaces; }
int LinuxNetBridge::GetInterfaceCount() { return iface_count; }

void LinuxNetBridge::SetInterfaceIP(const char* name, uint32_t ip, uint32_t mask) {
    LinuxNetInterface* iface = GetInterface(name);
    if (iface) { iface->ip_addr = ip; iface->netmask = mask; }
}

void LinuxNetBridge::SetInterfaceUp(const char* name, bool up) {
    LinuxNetInterface* iface = GetInterface(name);
    if (iface) iface->up = up;
}

//  dns

int LinuxNetBridge::Resolve(const char* hostname, uint32_t* ip_out) {
    if (!hostname || !ip_out) return -1;

    // built-in resolution
    if (ln_seq(hostname, "localhost")) { *ip_out = 0x7F000001; return 0; }
    if (ln_seq(hostname, "kurono"))    { *ip_out = 0x7F000001; return 0; }

    // simulate resolution
    *ip_out = 0x8EFB2108;  // example: 142.251.33.8
    return 0;
}

void LinuxNetBridge::SetDNS(uint32_t primary, uint32_t secondary) {
    dns_primary = primary;
    dns_secondary = secondary;
}

void LinuxNetBridge::GetDNS(uint32_t* primary, uint32_t* secondary) {
    if (primary) *primary = dns_primary;
    if (secondary) *secondary = dns_secondary;
}

//  byte order

uint16_t LinuxNetBridge::Htons(uint16_t v) {
    return (v >> 8) | (v << 8);
}

uint16_t LinuxNetBridge::Ntohs(uint16_t v) {
    return Htons(v);
}

uint32_t LinuxNetBridge::Htonl(uint32_t v) {
    return ((v >> 24) & 0xFF) | ((v >> 8) & 0xFF00) |
           ((v << 8) & 0xFF0000) | ((v << 24) & 0xFF000000);
}

uint32_t LinuxNetBridge::Ntohl(uint32_t v) {
    return Htonl(v);
}

void LinuxNetBridge::IpToStr(uint32_t ip, char* buf, int max) {
    int p = 0;
    for (int i = 3; i >= 0; i--) {
        int octet = (ip >> (i * 8)) & 0xFF;
        if (octet >= 100) { if (p < max - 1) buf[p++] = '0' + (octet / 100); }
        if (octet >= 10)  { if (p < max - 1) buf[p++] = '0' + ((octet / 10) % 10); }
        if (p < max - 1) buf[p++] = '0' + (octet % 10);
        if (i > 0 && p < max - 1) buf[p++] = '.';
    }
    buf[p] = 0;
}

//  output formatters

void LinuxNetBridge::Ifconfig(char* out, int max_out) {
    int p = 0;
    char ipbuf[16];

    for (int i = 0; i < iface_count; i++) {
        LinuxNetInterface* iface = &interfaces[i];

        p = pa(out, p, max_out, iface->name);
        p = pa(out, p, max_out, ": flags=");
        p = pd(out, p, max_out, iface->up ? 4163 : 0);
        p = pa(out, p, max_out, "<");
        if (iface->up) p = pa(out, p, max_out, "UP,");
        if (iface->loopback) p = pa(out, p, max_out, "LOOPBACK,");
        else p = pa(out, p, max_out, "BROADCAST,");
        p = pa(out, p, max_out, "RUNNING,MULTICAST>  mtu ");
        p = pd(out, p, max_out, iface->mtu);
        p = pa(out, p, max_out, "\n");

        p = pa(out, p, max_out, "        inet ");
        IpToStr(iface->ip_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf);
        p = pa(out, p, max_out, "  netmask ");
        IpToStr(iface->netmask, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf);
        if (!iface->loopback) {
            p = pa(out, p, max_out, "  broadcast ");
            IpToStr(iface->broadcast, ipbuf, sizeof(ipbuf));
            p = pa(out, p, max_out, ipbuf);
        }
        p = pa(out, p, max_out, "\n");

        if (!iface->loopback) {
            p = pa(out, p, max_out, "        ether ");
            for (int j = 0; j < 6; j++) {
                const char* hex = "0123456789abcdef";
                if (p < max_out - 1) out[p++] = hex[iface->mac[j] >> 4];
                if (p < max_out - 1) out[p++] = hex[iface->mac[j] & 0xF];
                if (j < 5 && p < max_out - 1) out[p++] = ':';
            }
            p = pa(out, p, max_out, "\n");
        }

        p = pa(out, p, max_out, "        RX packets ");
        p = pd(out, p, max_out, (int)iface->rx_packets);
        p = pa(out, p, max_out, "  bytes ");
        p = pd(out, p, max_out, (int)iface->rx_bytes);
        p = pa(out, p, max_out, "\n        TX packets ");
        p = pd(out, p, max_out, (int)iface->tx_packets);
        p = pa(out, p, max_out, "  bytes ");
        p = pd(out, p, max_out, (int)iface->tx_bytes);
        p = pa(out, p, max_out, "\n\n");
    }
    out[p] = 0;
}

void LinuxNetBridge::IpAddr(char* out, int max_out) {
    Ifconfig(out, max_out);  // same output format for now
}

void LinuxNetBridge::Netstat(char* out, int max_out) {
    int p = 0;
    p = pa(out, p, max_out, "Active Internet connections\n");
    p = pa(out, p, max_out, "Proto Recv-Q Send-Q Local Address        Foreign Address      State\n");

    char ipbuf[16];
    for (int i = 0; i < LNET_MAX_SOCKETS; i++) {
        if (!sockets[i].active) continue;
        LinuxSocket* s = &sockets[i];

        p = pa(out, p, max_out, s->type == LSOCK_STREAM ? "tcp   " : "udp   ");
        p = pd(out, p, max_out, s->recv_len); p = pa(out, p, max_out, "      ");
        p = pd(out, p, max_out, s->send_len); p = pa(out, p, max_out, "      ");

        IpToStr(s->local_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf); p = pa(out, p, max_out, ":");
        p = pd(out, p, max_out, s->local_port);

        p = pa(out, p, max_out, "   ");
        IpToStr(s->remote_addr, ipbuf, sizeof(ipbuf));
        p = pa(out, p, max_out, ipbuf); p = pa(out, p, max_out, ":");
        p = pd(out, p, max_out, s->remote_port);

        const char* st;
        switch (s->state) {
            case LSOCK_CLOSED:     st = "CLOSED"; break;
            case LSOCK_CREATED:    st = "CREATED"; break;
            case LSOCK_BOUND:      st = "BOUND"; break;
            case LSOCK_LISTENING:  st = "LISTEN"; break;
            case LSOCK_CONNECTED:  st = "ESTABLISHED"; break;
            case LSOCK_CONNECTING: st = "SYN_SENT"; break;
            default: st = "???"; break;
        }
        p = pa(out, p, max_out, "   ");
        p = pa(out, p, max_out, st);
        p = pa(out, p, max_out, "\n");
    }
    out[p] = 0;
}

//  shell commands

void LinuxNetBridge::RegisterShellCommands(void* shell) {
    Shell* sh = (Shell*)shell;
    if (!sh) return;
    sh->RegisterCommand("ifconfig_l", cmd_ifconfig, "Linux network interface config");
    sh->RegisterCommand("ip_l",       cmd_ip,       "Linux IP configuration");
    sh->RegisterCommand("netstat_l",  cmd_netstat,  "Linux network connections");
    sh->RegisterCommand("ping_l",     cmd_ping,     "Linux ping");
    sh->RegisterCommand("nslookup",   cmd_nslookup, "DNS lookup");
}

int LinuxNetBridge::cmd_ifconfig(void*, int, const char**, char* out, int mx) {
    Ifconfig(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_ip(void*, int, const char**, char* out, int mx) {
    IpAddr(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_netstat(void*, int, const char**, char* out, int mx) {
    Netstat(out, mx);
    return (int)strlen(out);
}

int LinuxNetBridge::cmd_ping(void*, int argc, const char** argv, char* out, int mx) {
    int p = 0;
    if (argc < 2) {
        return pa(out, 0, mx, "Usage: ping <hostname|ip>\n");
    }

    const char* host = argv[1];
    uint32_t ip;
    Resolve(host, &ip);

    char ipbuf[16];
    IpToStr(ip, ipbuf, sizeof(ipbuf));

    p = pa(out, p, mx, "PING ");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, " (");
    p = pa(out, p, mx, ipbuf);
    p = pa(out, p, mx, ") 56(84) bytes of data.\n");

    for (int i = 0; i < 4; i++) {
        p = pa(out, p, mx, "64 bytes from ");
        p = pa(out, p, mx, ipbuf);
        p = pa(out, p, mx, ": icmp_seq=");
        p = pd(out, p, mx, i + 1);
        p = pa(out, p, mx, " ttl=64 time=0.");
        p = pd(out, p, mx, 1 + i);
        p = pa(out, p, mx, " ms\n");
    }

    p = pa(out, p, mx, "\n--- ");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, " ping statistics ---\n");
    p = pa(out, p, mx, "4 packets transmitted, 4 received, 0% packet loss\n");
    p = pa(out, p, mx, "rtt min/avg/max/mdev = 0.1/0.2/0.4/0.1 ms\n");
    return p;
}

int LinuxNetBridge::cmd_nslookup(void*, int argc, const char** argv, char* out, int mx) {
    int p = 0;
    if (argc < 2) {
        return pa(out, 0, mx, "Usage: nslookup <hostname>\n");
    }

    const char* host = argv[1];
    uint32_t ip;
    Resolve(host, &ip);

    char ipbuf[16];
    IpToStr(ip, ipbuf, sizeof(ipbuf));
    char dns_buf[16];
    IpToStr(dns_primary, dns_buf, sizeof(dns_buf));

    p = pa(out, p, mx, "Server:\t\t");
    p = pa(out, p, mx, dns_buf);
    p = pa(out, p, mx, "\nAddress:\t");
    p = pa(out, p, mx, dns_buf);
    p = pa(out, p, mx, "#53\n\nNon-authoritative answer:\n");
    p = pa(out, p, mx, "Name:\t");
    p = pa(out, p, mx, host);
    p = pa(out, p, mx, "\nAddress: ");
    p = pa(out, p, mx, ipbuf);
    p = pa(out, p, mx, "\n");
    return p;
}
